spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: hmall         # ????????
    password: 123           # ?????
    virtual-host: /hmall     # ??????
    listener:
      simple:
        prefetch: 1   #??????1? ???????????